### ISSUE TITLE
Not getting notified when kicked from a channel

### ISSUE THREAD

**Issue by rahulkalluri** [ftc2/interview-notify#5] opened 2023-06-22 15:45 UTC
**Code:**

- ` python .\interview_notify.py --topic []-interview --log-dir C:\Users\[name]\AppData\Roaming\mIRC\logs\ --nick []`

Scenario:
`[02:12] * You were kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))`

**Problem:**

- Occasionally in a certain invite channel for a music tracker, the Gatekeeper will be booted from the server and will force everyone to requeue. I was not notified of when I was kicked. 

I tested the `<bot> is currently interviewing` message in the channel and the notifier works fine there but didn't tell me when I was booted. 

**Additional suggestion:** 
- Is there a way to detect when the bot itself is booted from a channel? This notification would help let me know when I need to requeue

**Comment by ftc2** [comment] 2023-06-22 17:13
> Scenario: `[02:12] * You were kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))`
> 
> **Problem:**
> 
>     * Occasionally in a certain invite channel for a music tracker, the Gatekeeper will be booted from the server and will force everyone to requeue.

sometimes irc servers temporarily split from each other. that is called a netsplit. the irc server you were connected to split from the irc network, or Gatekeeper's server split. the obvious solution would be to connect to the same server Gatekeeper uses, but you can't. it's not public ;(

looks like your kick was not detected because your log format uses `You` instead of your nick.

https://github.com/ftc2/interview-notify/blob/76837f6dd0e0037556bdf1e76bac3e99f0b20291/interview_notify.py#L82-L84
https://github.com/ftc2/interview-notify/blob/76837f6dd0e0037556bdf1e76bac3e99f0b20291/interview_notify.py#L113-L115

as a low-effort workaround, you could consider running a second instance of the notifier with your nick set to `You`. maybe that would work.

>     * Is there a way to detect when the bot itself is booted from a channel? This notification would help let me know when I need to requeue

the notifier does detect netsplits, but you didn't share a log of that event, so i can't guess why it didn't work.

https://github.com/ftc2/interview-notify/blob/76837f6dd0e0037556bdf1e76bac3e99f0b20291/interview_notify.py#L79-L81

**Comment by rahulkalluri** [comment] 2023-06-22 18:00
Hmm okay I see. I'm attaching a log of the last hour before I was kicked. I can definitely run another instance of the notifier set to 'You'. 

```
[01:07] * User_ (eXil3d@red-9kt.bra.v9d2p9.IP) has joined #red-invites
[01:07] * Gatekeeper sets mode: +b User_!*@*
[01:07] * User_ was kicked by Gatekeeper (Please choose a less generic nick (does not expire))
[01:14] * Gatekeeper sets mode: +b *!*@red-ag7.smu.pcoaai.IP
[01:14] * Scccccc was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[01:22] * Gatekeeper sets mode: -b User_!*@*
[01:29] * Gatekeeper sets mode: -b *!*@red-ag7.smu.pcoaai.IP
[01:29] * Sccccc (Sccccc@red-ag7.smu.pcoaai.IP) has joined #red-invites
[01:29] <Sccccc> !queue https://www.speedtest.net/result/14899027925.png
[02:01] * Agrajag (Agrajag@red-81d.eik.4bu4et.IP) Quit (Ping timeout: 121 seconds)
[02:01] * &ChanServ (services@services.int) Quit (*.net *.split)
[02:01] * ~zed (1@zed.sysop.redacted.ch) Quit (*.net *.split)
[02:01] * %Gatekeeper (gatekeeper@Gatekeeper.bot.redacted.ch) Quit (*.net *.split)
[02:02] * Gatekeeper (gatekeeper@Gatekeeper.bot.redacted.ch) has joined #red-invites
[02:02] * zed (1@zed.sysop.redacted.ch) has joined #red-invites
[02:02] * ChanServ (services@services.int) has joined #red-invites
[02:02] * *.scratch-network.net sets mode: +hqoao Gatekeeper zed zed ChanServ ChanServ
[02:03] <notgeneric> !queue https://www.speedtest.net/result/14899127447.png
[02:06] <quilotix> !queue https://www.speedtest.net/result/14899136468.png
[02:07] <eggzenbeanz> !queue https://www.speedtest.net/result/14899140274.png
[02:08] <Sccccc> !queue https://www.speedtest.net/result/14899141556.png
[02:11] <Virtis> !queue https://www.speedtest.net/result/14899150309.png
[02:11] * Agrajag (Agrajag@red-81d.eik.4bu4et.IP) has joined #red-invites
[02:12] * Gatekeeper sets mode: +b *!*@red-q2d.jli.jh6ifk.IP
[02:12] * babbles_mcdrinksalot was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-8vu.urg.8glf3r.IP
[02:12] * firefly9870 was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-47m.vs2.a5du2n.IP
[02:12] * BoiestBo was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-ve7.abg.nqnjiu.IP
[02:12] * varplysuef was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-tkd.qdr.3fm5ie.IP
[02:12] * Krovio was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-j62.l8t.35q2nu.IP
[02:12] * Gareth was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-tg2.171.4ivbq3.IP
[02:12] * audiofreq was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-4a2.6qr.57ohgm.IP
[02:12] * Mythical was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-l6g.k6v.ed22ms.IP
[02:12] * SkulKing was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-rt7.m5h.4j19c7.IP
[02:12] * trustissues was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-r83.9hq.50t0hv.IP
[02:12] * p4free95 was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-otk.8sq.8lbvnk.IP
[02:12] * ZeroTheHero was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-a60.fgo.rhvgn0.IP
[02:12] * warofpop was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-4ar.jjf.a6qp0q.IP
[02:12] * Zypher was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-ipu.rst.56a502.IP
[02:12] * Grizzley was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-eva.qm4.drkh7a.IP
[02:12] * garf250 was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-7fd.uib.8glf3r.IP
[02:12] * Hopps was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-tv8.hjr.djj23d.IP
[02:12] * SeniorMoistener was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-lng.59q.qvcglk.IP
[02:12] * StaciaKazuha was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-nvr.2v0.o1ckh0.IP
[02:12] * glugbrisbane was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[02:12] * Gatekeeper sets mode: +b *!*@red-7fe.n58.sr40fv.IP
[02:12] * You were kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
Session Close: Thu Jun 22 02:12:49 2023
```

The Gatekeeper was kicked yesterday and the day before yesterday between 1-4am, and since I wasn't notified I couldn't requeue. Not sure what I'm doing incorrectly tho

**Comment by rahulkalluri** [comment] 2023-06-22 18:02
Here is the log from 2 nights ago where the Gatekeeper quit but I received no message:

```
[04:08] * ~zed (1@zed.sysop.redacted.ch) Quit (*.net *.split)
[04:08] * %Gatekeeper (gatekeeper@Gatekeeper.bot.redacted.ch) Quit (*.net *.split)
[04:09] * Gatekeeper (gatekeeper@Gatekeeper.bot.redacted.ch) has joined #red-invites
[04:09] * zed (1@zed.sysop.redacted.ch) has joined #red-invites
[04:09] * ChanServ (services@services.int) has joined #red-invites
[04:09] * *.scratch-network.net sets mode: +hqoao Gatekeeper zed zed ChanServ ChanServ
[04:11] <notgeneric> !queue https://www.speedtest.net/result/14894998645.png
[04:12] <StaciaKazuha> !queue https://www.speedtest.net/result/14895002627.png
[04:12] <notgeneric> Requeue time guys
[04:12] <Virtis> !queue https://www.speedtest.net/result/14895002406.png
[04:19] * Gatekeeper sets mode: +b *!*@red-q2d.jli.jh6ifk.IP
[04:19] * babbles_mcdrinksalot was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-8vu.urg.8glf3r.IP
[04:19] * firefly9870 was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-47m.vs2.a5du2n.IP
[04:19] * BoiestBo was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-tkd.qdr.3fm5ie.IP
[04:19] * Krovio was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-l6g.k6v.ed22ms.IP
[04:19] * Skul_King was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-otk.8sq.8lbvnk.IP
[04:19] * ZeroTheHero was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-ve7.abg.nqnjiu.IP
[04:19] * varplysuef was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-plc.aqk.gd385a.IP
[04:19] * tadeas was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-5ve.5aa.vni54l.IP
[04:19] * astroman was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-rt7.m5h.4j19c7.IP
[04:19] * trustissues was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-ipu.rst.56a502.IP
[04:19] * Grizzley was kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
[04:19] * Gatekeeper sets mode: +b *!*@red-bt0.ag7.bhtjn4.IP
[04:19] * You were kicked by Gatekeeper (No idling. You may not stay in this channel without !queueing. (expires in 14m 59s))
Session Close: Wed Jun 21 04:19:40 2023
```

**Comment by ftc2** [comment] 2023-06-22 18:32
the relevant line:

> `[02:01] * %Gatekeeper (gatekeeper@Gatekeeper.bot.redacted.ch) Quit (*.net *.split)`

https://github.com/ftc2/interview-notify/blob/76837f6dd0e0037556bdf1e76bac3e99f0b20291/interview_notify.py#L79-L81

the problem is `'Quit' != 'quit'`. wtf, why does mIRC capitalize "Quit" and not "joined" or any other event?

this probably fixes it: https://github.com/ftc2/interview-notify/commit/1bb75c0ad29d266fb5f0c451c232b86cb70cd6d4

**Comment by rahulkalluri** [comment] 2023-06-22 21:28
So only the interviewing line threw me an alert but the Gatekeeper Quit line still didn't. 
**IRC:** 
```
[16:26] <kingcurry> Gatekeeper Quit (*.net *.split)
[16:26] <kingcurry> Currently interviewing: kingcurry
```

**Logs:**
```
2023-06-22 16:26:47 DEBUG: ♥01[16:26] <kingcurry> Gatekeeper Quit (*.net *.split)

2023-06-22 16:27:00 DEBUG: ♥01[16:26] <kingcurry> Currently interviewing: kingcurry

2023-06-22 16:27:00 INFO: YOUR INTERVIEW IS HAPPENING ❗
2023-06-22 16:27:00 DEBUG: Starting new HTTPS connection (1): ntfy.sh:443
2023-06-22 16:27:00 DEBUG: https://ntfy.sh:443 "POST /red-interview HTTP/1.1" 200 274
```

**Comment by ftc2** [comment] 2023-06-22 22:11
fixed in https://github.com/ftc2/interview-notify/commit/4c7297507690d72b097b26974835da8ca56f5b2a

**Closed** 2023-06-22 22:11 UTC
